// Custom configuration matching Laravel's config/custom.php

export const customConfig = {
  user: {
    profile: ['Self', 'Parents', 'Friends', 'Guardian', 'Sibling'],
    gender: ['Male', 'Female'],
    mat_status: ['Unmarried', 'Widow/Widower', 'Divorcee', 'Seperated', 'Awaiting Divorce'],
  },

  options_type: {
    moonsigns: [
      'Aries(मेष)',
      'Taurus(वृषभ)',
      'Gemini(मिथुन)',
      'Cancer(कर्क)',
      'Leo(सिंह)',
      'Virgo(कन्या)',
      'Libra(तुला)',
      'Scorpious(वृश्चिक)',
      'Sagittarius(धनु)',
      'Capricornus(मकर)',
      'Aquarius(कुम्भ)',
      'Pisces(मीन)',
    ],
    occupation: [
      'Private',
      'Government',
      'Lawyer',
      'Professor',
      'Teacher',
      'Doctor',
      'Dentist',
      'Chartered Accountant',
      'Software Professional',
      'Engineer',
      'Lecturer',
      'Business',
      'Accountant',
      'HR',
      'Civil services',
      'Management',
      'Self-employed',
      'will tell later',
    ],
    education: [
      'BE B.tech',
      'M Tech',
      'BCA',
      'MCA',
      'MBA PGDM',
      'BBA',
      'CA',
      'B Pharma',
      'M Pharma',
      'PhD Doctorate',
      'BSc',
      'MSc',
      'BA',
      'MA',
      'M. VSc',
      'PGDBM',
      'BAMS',
      'CCNA',
      'MCSE',
      'Under Graduate',
      'Post Graduate',
      'BLib',
      'Mlib',
      'BPEd',
      'MDS',
      'BHMS',
      'D Pharma',
      'BSc Nursing',
      'BArch',
      'BCom',
      'MBBS',
    ],
    height: [
      'Below 4ft',
      '4ft 1in',
      '4ft 2in',
      '4ft 3in',
      '4ft 4in',
      '4ft 5in',
      '4ft 6in',
      '4ft 7in',
      '4ft 8in',
      '4ft 9in',
      '4ft 10in',
      '4ft 11in',
      '5ft',
      '5ft 1in',
      '5ft 2in',
      '5ft 3in',
      '5ft 4in',
      '5ft 5in',
      '5ft 6in',
      '5ft 7in',
      '5ft 8in',
      '5ft 9in',
      '5ft 10in',
      '5ft 11in',
      '6ft',
      '6ft 1in',
      '6ft 2in',
      '6ft 3in',
      '6ft 4in',
      '6ft 5in',
      '6ft 6in',
      '6ft 7in',
      '6ft 8in',
      '6ft 9in',
      '6ft 10in',
      '6ft 11in',
      '7ft',
      'Above 7ft',
    ],
    Diet: ['Vegetarian', 'Eggetarian', 'Non-Vegetarian', 'Vegan'],
    Income: [
      'No income',
      'Rs50,001-Rs100,000',
      'Rs100,001-Rs200,000',
      'Rs200,001-Rs300,000',
      'Rs300,001-Rs400,000',
      'Rs400,001-Rs500,000',
      'Rs500,001-Rs750,000',
      'Rs750,001-Rs10,00,000',
      'Rs10,00,001-Rs15,00,000',
      'Rs15,00,001-Rs20,00,000',
      'Rs20,00,001-Rs25,00,000',
      'Will Tell Later',
    ],
  },
};
